"""Update claim model

Revision ID: 615ed8c2794a
Revises: 4f924d7a4941
Create Date: 2024-04-02 16:51:45.632404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615ed8c2794a'
down_revision = '4f924d7a4941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
        batch_op.alter_column('expensetype',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('expensetype',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
