"""Allow claim attributes except Title to be null

Revision ID: 6fc382141939
Revises: 615ed8c2794a
Create Date: 2024-04-08 16:09:44.328403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc382141939'
down_revision = '615ed8c2794a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
        batch_op.alter_column('expensetype',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('expensetype',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
