"""Update amount column in Claim model

Revision ID: 70522ef5a346
Revises: 47fe20c62081
Create Date: 2024-03-26 20:37:42.320116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70522ef5a346'
down_revision = '47fe20c62081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
