"""Remove status column and update ClaimStatus enum

Revision ID: a9f2232d532d
Revises: beb6ed0ddcbf
Create Date: 2024-03-29 11:54:49.088937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9f2232d532d'
down_revision = 'beb6ed0ddcbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_column('status')

    sa.Enum('PENDING', 'APPROVED', 'DENIED', name='ClaimStatus').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'APPROVED', 'DENIED', name='ClaimStatus').create(op.get_bind())
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'DENIED', name='ClaimStatus', create_type=False), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
