"""Add appeal table

Revision ID: c3ac42ab9fb3
Revises: 70522ef5a346
Create Date: 2024-03-27 11:19:42.560916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ac42ab9fb3'
down_revision = '70522ef5a346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appeal')
    # ### end Alembic commands ###
