"""Re-add status column to Claim

Revision ID: d9c1f53e972c
Revises: a9f2232d532d
Create Date: 2024-03-29 11:57:15.408263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9c1f53e972c'
down_revision = 'a9f2232d532d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'DENIED', name='claimstatus').create(op.get_bind())
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'APPROVED', 'DENIED', name='claimstatus', create_type=False), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_column('status')

    sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'DENIED', name='claimstatus').drop(op.get_bind())
    # ### end Alembic commands ###
